FROM python:3.5.1-slim
RUN apt-get update
RUN apt-get -y install build-essential gcc
RUN pip install --no-cache-dir fabric3 jinja2

# fabric3 = for streamlining the use of SSH for application deployment or systems administration tasks.
# jinia2 = templating language for python