# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-21 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import weekday_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('weekdays', weekday_field.fields.WeekdayField(max_length=14)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('external_id', models.CharField(db_index=True, max_length=200, null=True)),
                ('precedence', models.IntegerField(default=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=80, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='ep.Device')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceParameterType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=80)),
                ('description', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50)),
                ('description', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, default='default', max_length=200, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GatewayProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, null=True)),
                ('value', models.CharField(max_length=200, null=True)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='ep.Gateway')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_name', models.CharField(max_length=100, null=True)),
                ('floor', models.CharField(max_length=10, null=True)),
                ('building', models.CharField(max_length=50, null=True)),
                ('external_id', models.CharField(db_index=True, default='default', max_length=200, null=True)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='ep.Gateway')),
            ],
        ),
        migrations.CreateModel(
            name='NodeProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, null=True)),
                ('value', models.CharField(max_length=200, null=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='ep.Node')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleDeviceParameterGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_parameters', models.ManyToManyField(related_name='schedule', to='ep.DeviceParameter')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='site', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, null=True)),
                ('value', models.CharField(max_length=200, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='ep.Site')),
            ],
        ),
        migrations.CreateModel(
            name='StateChangeEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('OD', 'C'), ('SC', 'A'), ('EB', 'E')], max_length=2)),
                ('date_time', models.DateTimeField()),
                ('previous_value', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('new_value', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('device_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ep.DeviceParameter')),
            ],
            options={
                'get_latest_by': 'date_time',
                'ordering': ['-date_time'],
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('enabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TariffBandProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, null=True)),
                ('value', models.CharField(max_length=200, null=True)),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='ep.Band')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.AddField(
            model_name='node',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='ep.Vendor'),
        ),
        migrations.AddField(
            model_name='gateway',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gateways', to='ep.Site'),
        ),
        migrations.AddField(
            model_name='gateway',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gateways', to='ep.Vendor'),
        ),
        migrations.AddField(
            model_name='deviceparameter',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_parameters', to='ep.DeviceParameterType'),
        ),
        migrations.AddField(
            model_name='device',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='ep.Node'),
        ),
        migrations.AddField(
            model_name='device',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='ep.DeviceType'),
        ),
        migrations.AddField(
            model_name='device',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='ep.Vendor'),
        ),
        migrations.AddField(
            model_name='band',
            name='tariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bands', to='ep.Tariff'),
        ),
        migrations.AlterUniqueTogether(
            name='node',
            unique_together=set([('gateway', 'external_id')]),
        ),
    ]
