# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-21 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ep', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrefectDeviceParameterConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power_consumption', models.DecimalField(decimal_places=2, max_digits=7)),
                ('line', models.CharField(max_length=2)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='ep.Device')),
            ],
            options={
                'verbose_name': 'Prefect Device Configuration',
            },
        ),
    ]
